service: leo-peru-packing-analyzer

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  memorySize: 512
  timeout: 30
  environment:
    PYTHONPATH: /var/runtime:/var/task/vendor
  apiGateway:
    binaryMediaTypes:
      - '*/*'

functions:
  processExcel:
    handler: lambda_function.lambda_handler
    events:
      - http:
          path: process
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer: true
    slim: true
    strip: false
    noDeploy:
      - numpy
      - pandas