name: Deploy to AWS Lambda

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -t ./vendor
        pip install pandas -t ./vendor
        pip install openpyxl -t ./vendor
    
    - name: Create deployment package
      run: |
        cp lambda_function.py ./vendor/
        cd vendor && zip -r ../deployment.zip . -x "*.pyc" "*.pyo"
    
    - name: Deploy to Lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: eu-north-1
      run: |
        aws lambda update-function-code \
          --function-name leo-peru-process-excel \
          --zip-file fileb://deployment.zip \
          --region eu-north-1
    
    - name: Deploy frontend to GitHub Pages
      run: |
        mkdir -p public
        cp index.html public/
        touch public/.nojekyll
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public